# version: '3.8'

# services:
#   searxng:
#     image: searxng/searxng:latest
#     volumes:
#       - ./searxng/settings.yml:/etc/searxng/settings.yml
#     ports:
#       - "8080:8080"
#     networks:
#       - reach

#   backend:
#     build: 
#       context: ./backend
#       dockerfile: Dockerfile
#     volumes:
#       - ./backend:/usr/src/app
#       - ./reach_core:/usr/src/app/reach_core
#     environment:
#       SEARX_URL: http://searxng:8080
#       OPENAI_API_KEY: ${OPENAI_API_KEY}
#     ports:
#       - "8000:8000"
#     networks:
#       - reach

#   frontend:
#     build:
#       context: ./frontend
#       dockerfile: Dockerfile.nextjs
#       secrets:
#         - OPENAI_API_KEY
#     volumes:
#       - ./frontend/src:/usr/src/app/src
#       - ./frontend/public:/usr/src/app/public
#       - /usr/src/app/.next
#       - /usr/src/app/node_modules
#     ports:
#       - "3000:3000"
#     environment:
#       - NEXT_PUBLIC_BACKEND_URL=backend:8000
#       - OPENAI_API_KEY=${OPENAI_API_KEY}
#       - SEARX_URL=http://searxng:8080
#       - WATCHPACK_POLLING=true
#     depends_on:
#       - backend
#     networks:
#       - reach

# secrets:
#   OPENAI_API_KEY:
#     file: ./frontend/.env.local

# networks:
#   reach:
#     driver: bridge

#PROD
version: '3.8'
services:
  searxng:
    image: searxng/searxng:latest
    volumes:
      - ./searxng/settings.yml:/etc/searxng/settings.yml
    ports:
      - "8080:8080"
    networks:
      - reach

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      SEARX_URL: http://searxng:8080
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "8000:8000"
    networks:
      - reach

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.nextjs
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=https://themagi.systems
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SEARX_URL=http://searxng:8080
    depends_on:
      - backend
    networks:
      - reach

networks:
  reach:
    driver: bridge