apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 500m
                memory: 512Mi
          image: reach13/reach_3/backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: SEARX_URL
              value: "http://searxng:8080"
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: openai-api-key
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: backend
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: backend
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`themagi.systems`) && PathPrefix(`/ws`)
      kind: Rule
      services:
        - name: backend
          port: 8000
      middlewares:
        - name: websocket
  tls:
    certResolver: myresolver
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: websocket
spec:
  headers:
    customRequestHeaders:
      Connection: Upgrade
      Upgrade: websocket