---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: reach13/reach_3/frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_BASE_URL
              value: "http://themagi.systems"
            - name: NEXT_PUBLIC_BACKEND_URL
              value: "http://themagi.systems"
            - name: DEPLOYMENT
              value: "PROD"
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: frontend-secrets
                  key: openai-api-key
            - name: SEARX_URL
              value: "http://searxng:8080"

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: frontend

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
spec:
  rules:
    - host: themagi.systems
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port: 
                  number: 3000