apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData:
  openai-api-key: ${OPENAI_API_KEY}

---
apiVersion: v1
kind: Secret
metadata:
  name: frontend-secrets
type: Opaque
stringData:
  openai-api-key: ${OPENAI_API_KEY}